import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';

import { Providers } from '../app/Providers';

import { cookies } from 'next/headers'
import { Betslip, BetsSummary, FootBar, NavBar } from '@/components'
import { CreateNewBet } from "@/components/Display/CreateNewBet";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()

  const initialChainId = cookieStore.get('appChainId')?.value
  const initialLiveState = JSON.parse(cookieStore.get('live')?.value || 'false')

  // console.log('initialChainId', initialChainId)

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Providers>
            <NavBar />

            <main>
              {children}  
            </main>
          
            <FootBar/>
            {/* <div className="mx-2">
              <BetsSummary />
              <CreateNewBet/>
              <Betslip />
            </div> */}

          </Providers>
      </body>
    </html>
  );
}
